; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D3F7A1B2-C4D5-4E6F-AF01-23456789ABCD}
AppName=Fuinha Network Monitor
AppVersion=3.0
AppPublisher=Vinicius Lacerda
DefaultDirName={autopf}\Fuinha
DefaultGroupName=Fuinha
AllowNoIcons=yes
; Require Administrator for installation
PrivilegesRequired=admin
OutputDir=..\dist
OutputBaseFilename=Fuinha_v3.0_Setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "brazilianportuguese"; MessagesFile: "compiler:Languages\BrazilianPortuguese.isl"
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\dist\main\main.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\dist\main\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{group}\Fuinha"; Filename: "{app}\main.exe"
Name: "{autodesktop}\Fuinha"; Filename: "{app}\main.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\main.exe"; Description: "{cm:LaunchProgram,Fuinha}"; Flags: nowait postinstall skipifsilent
